---
- hosts: demanda
  become: true
  become_user: root
  remote_user: rreis
  gather_facts: false
  tasks:
    - name: Criando usuario remoto
      user:
       name: usrfly
       comment: I1812-030292 - usuario de banco de dados
       shell: /bin/false
      tags: usrfly

    - name: Padrinozando senha 
      user:
       name: usrfly
       password: 'Hash da senha do usuário'
      tags: user
